---
'centos-64-x64':
  provider_specifics:
    vagrant:
      box: 'centos-64-x64-kvm-2'
      box_url: 'http://puppet-vagrant-boxes-ci.s3.amazonaws.com/centos-64-x64-kvm-2.box'
'fedora-18-x64':
  provider_specifics:
    vagrant:
      box: 'fedora-18-x64'
      box_url: 'http://radon.usersys.redhat.com/templates/boxes/fedora-18-x64.box'
'ubuntu-server-12042-x64':
  provider_specifics:
    vagrant:
      box: 'ubuntu-server-12042-x64-kvm-2'
      box_url: 'http://puppet-vagrant-boxes-ci.s3.amazonaws.com/ubuntu-server-12042-x64-kvm-2.box'
'debian-70-x64':
  facts:
    architecture: amd64
    kernel: Linux
    operatingsystem: Debian
    lsbdistid: Debian
    facterversion: "1.6.18"
    kernelmajversion: "3.2"
    kernelrelease: "3.2.0-4-amd64"
    kernelversion: "3.2.0"
    lsbdistcodename: wheezy
    lsbdistdescription: "Debian GNU/Linux 7.0 (wheezy)"
    lsbdistrelease: "7.0"
    lsbmajdistrelease: "7"
    operatingsystemrelease: "7.0"
    osfamily: Debian
    rubyversion: "1.9.3"
  provider_specifics:
    vagrant:
      box: 'debian-710-x64-kvm-2'
      box_url: 'http://puppet-vagrant-boxes-ci.s3.amazonaws.com/debian-710-x64-kvm-2.box'
'debian-60-x64':
  facts:
    kernel: Linux
    lsbmajdistrelease: "6"
    operatingsystemrelease: "6.0.7"
    kernelrelease: "2.6.32-5-amd64"
    osfamily: Debian
    lsbdistrelease: "6.0.7"
    lsbdistcodename: squeeze
    lsbdistdescription: "Debian GNU/Linux 6.0.7 (squeeze)"
    kernelversion: "2.6.32"
    operatingsystem: Debian
    kernelmajversion: "2.6"
    facterversion: "1.6.18"
    rubyversion: "1.8.7"
    lsbdistid: Debian
    architecture: amd64
  provider_specifics:
    vagrant:
      box: 'debian-607-x64-kvm-3'
      box_url: 'http://puppet-vagrant-boxes-ci.s3.amazonaws.com/debian-607-x64-kvm-3.box'
